### ISSUE TITLE
enforce HSTS too as we'll deploy with SSL 

### ISSUE THREAD

**Issue by tomwm** [ministryofjustice/atet#286]
https://www.pivotaltracker.com/story/show/81502606

**Comment by tomwm** [comment]
@mattmb do we still need this?

**Comment by mattmb** [comment]
Technically we haven't done this. However we do a permanent rewrite of HTTP to HTTPS which is functionally the same I think.

**Comment by tomwm** [comment]
Ok will close.

On 21 April 2015 at 15:53, Matthew Mead-Briggs <notifications@github.com>
wrote:

> Technically we haven't done this. However we do a permanent rewrite of
> HTTP to HTTPS which is functionally the same I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ministryofjustice/atet/issues/286#issuecomment-94829057>
> .
>



-- 
Tom Wynne-Morgan
Product Manager
*Ministry of Justice Digital Services*

*https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London
<https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London>
*

tom.wynne-morgan@digital.justice.gov.uk <tom.dolan@digital.justice.gov.uk>
