### ISSUE TITLE
"No reply" sender email

### ISSUE THREAD

**Issue by stevegraham** [ministryofjustice/atet#469]
Transactional emails have a sender of "no-reply@digital.justice.gov.uk", which is not in the user's interest. It may be the case that there is a problem with the email (broken links, missing information, etc) and replying to the email is the only way the user can proceed. We will set our sender or reply-to to go to our Zendesk instance.

Tasks:

- [ ] Customise Zendesk such that the email ends in "digital.justice.gov.uk" because "ministryofjustice.zendesk.com" is not acceptable for government transactional email.
- [ ] Update application config

cc @helenmott @tomwm

**Comment by tomwm** [comment]
@milror00 i think this is something we can/should do as part of updating the way we use zendesk
