### ISSUE TITLE
Error messages copy updates

### ISSUE THREAD

**Issue by cleargif** [ministryofjustice/atet#516]
https://docs.google.com/a/digital.justice.gov.uk/document/d/1jRMeOHOAWBI-3FhUSywga7G28NNCioUQWyYGbqqIMms/edit#heading=h.eyxcd8gtpyhf

**Comment by michaelelwin** [comment]
If fields are optional and field left empty, no error message should be displayed. If fields are optional and user has attempted to add information but information is not in the correct format, (eg incorrect postcode), then relevant error message should be generated. 

RESPONSE TO COMMENTS IN CAPITALS

/apply/claimant

require assistance: if yes the textarea can be left blank ERROR MESSAGE SHOULD BE GENERATED IF TEXT AREA LEFT BLANK. SEE DOC

/apply/additional-claimants
/apply/additional-claimants-upload
/apply/additional-respondents

all fields: cannot see where to change these error messages
/apply/representative N/A

Name: not validated
Postcode: cannot change invalid error message
Email: this field is optional, but added the entry into the locale file
/apply/respondent N/A

Work address: All fields marked as optional but they are validated apart from County and Phone
/apply/employment
/apply/claim-type
/apply/claim-outcome
/apply/additional-information

IF OPTIONAL, NONE SHOULD BE VALIDATED, UNLESS USER ENTERS INFO, THEN INVALIDATED IF INCORRECT FORMAT INSERTED 

all fields are optional
/apply/claim-details

similar claims: fields are optional
