### ISSUE TITLE
Jadu API error handling

### ISSUE THREAD

**Issue by mattmb** [ministryofjustice/atet#624]
Tidy up the error handling code for the Jadu API, so that we make sure we log the HTTP response and status code *before* we start trying to parse out the error messages that Jadu send.

**Comment by mattmb** [comment]
https://github.com/ministryofjustice/atet/blob/master/app/services/jadu/claim.rb#L18

This line blows up because values_at isn't delegated in the ParsedResponse object.

**Comment by mattmb** [comment]
@tomwm you might want to prioritise this because it will be hard to debug any claims that get rejected by Jadu without a fix. Should be a nice easy one for @dan-palmer or @stevegraham :smile:

**Comment by tomwm** [comment]
yup, its in PT at the top of the list https://www.pivotaltracker.com/story/show/88328330
