### ISSUE TITLE
Remove beta label

### ISSUE THREAD

**Issue by Demwunz** [ministryofjustice/atet#664]
pivotal https://www.pivotaltracker.com/story/show/91096874

**Comment by Demwunz** [comment]
https://github.com/ministryofjustice/atet/commit/9684c5cda128b1ab0270753c0530c4a90bd7ef17

**Comment by tomwm** [comment]
@demwunz do you want to create a PR for this and get it reviewed. Im looking to potentially release it tomorrow.
