### ISSUE TITLE
Validate All Date Fields

### ISSUE THREAD

**Issue by milror00** [ministryofjustice/atet#675]
ensure all year date fields have 4 digits

**Comment by michaelelwin** [comment]
All error message copy is in the master doc - https://docs.google.com/a/digital.justice.gov.uk/document/d/1jRMeOHOAWBI-3FhUSywga7G28NNCioUQWyYGbqqIMms/edit

Here's one specific to DOB. Obviously only include copy after the colon.  

Error (field blank): Please enter the claimant’s date of birth
Error (field invalid): Please enter the date of birth in the correct format (DD/MM/YYYY)
