### ISSUE TITLE
Confirm attachment status on every claim confirmation page and email

### ISSUE THREAD

**Issue by milror00** [ministryofjustice/atet#678]
Currently it only displays when there is an attachment. 

To give users peace of mind:
- Always display an 'attachments included'  section
- display 'none' when there are no attachments.

Under

**Comment by dan-palmer** [comment]
So if it looked like this if no file is attached we'd be happy?
![claim_details_no_attachment](https://cloud.githubusercontent.com/assets/1006365/7357937/fdf2d596-ed29-11e4-8c0a-a72ef4a70b7d.png)
@tomwm @milror00

**Comment by tomwm** [comment]
Yes, that's great. Would need to be the same on the confirmation emails,
which I believe are generated off that code anyway. But double check.
