### ISSUE TITLE
Timeout text

### ISSUE THREAD

**Issue by Demwunz** [ministryofjustice/atet#682]
https://www.pivotaltracker.com/story/show/87822390

**Comment by tomwm** [comment]
Timeout message text is currently not what's in the master doc.
https://docs.google.com/a/digital.justice.gov.uk/document/d/1h0V_N7wWygMceT7bmTptDoK1WTW0DeMmWqNOIKX_i08/edit#bookmark=id.zh20ewbltrt5

**Comment by tomwm** [comment]
@demwunz can you raise a PR for this and review...if its ready to go in for a release tomorrow.

**Comment by Demwunz** [comment]
@tomwm raised

**Comment by tomwm** [comment]
:)

**Comment by Demwunz** [comment]
https://github.com/ministryofjustice/atet/pull/711
