### ISSUE TITLE
Change copy around remission application

### ISSUE THREAD

**Issue by tomwm** [ministryofjustice/atet#699]
On 'your fee' page we need to add text. The lawyers want what is below but we should massage it a little

“Having read the guidance do you submit an application for remission?”
 It should then say next to the yes box –
"By ticking this box you have made a fee remission application.  If you do not complete the requisite form and provide supporting evidence to the Tribunal within seven days your fee remission application will be rejected”.

**Comment by michaelelwin** [comment]
copy written - suggesting a drop down if user clicks they want to apply for remission 

https://docs.google.com/a/digital.justice.gov.uk/document/d/1jRMeOHOAWBI-3FhUSywga7G28NNCioUQWyYGbqqIMms/edit#bookmark=id.3wcnq8swf0km

**Comment by michaelelwin** [comment]
BTW also noticed that the link to the remission form is not correct at present

**Comment by dan-palmer** [comment]
Lets make that into a separate issue. 

If somebody can get an updated link to the document it can be updated.

**Comment by tomwm** [comment]
@michaelelwin can you action @dan-palmer comment above. Thanks

**Comment by michaelelwin** [comment]
@dan-palmer @tomwm here is the correct link for the fee remission form http://hmctsformfinder.justice.gov.uk/courtfinder/forms/ex160-eng.pdf

**Comment by tomwm** [comment]
@michaelelwin lets put that in a new issue. Practice your waffle/Github
skills!


On 24 April 2015 at 10:41, Michael Elwin <notifications@github.com> wrote:

> @dan-palmer <https://github.com/dan-palmer> @tomwm
> <https://github.com/tomwm> here is the correct link for the fee remission
> form http://hmctsformfinder.justice.gov.uk/courtfinder/forms/ex160-eng.pdf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ministryofjustice/atet/issues/699#issuecomment-95871940>
> .
>



-- 
Tom Wynne-Morgan
Product Manager
*Ministry of Justice Digital Services*

*https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London
<https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London>
*

tom.wynne-morgan@digital.justice.gov.uk <tom.dolan@digital.justice.gov.uk>

**Comment by michaelelwin** [comment]
@tomwm I got mad waffle skillz

**Comment by michaelelwin** [comment]
@tomwm new copy added to encourage users to email fee remission claim

https://docs.google.com/a/digital.justice.gov.uk/document/d/1jRMeOHOAWBI-3FhUSywga7G28NNCioUQWyYGbqqIMms/edit#bookmark=id.3wcnq8swf0km

Also created new issue (721) for remission link

**Comment by tomwm** [comment]
fixed by #723
