### ISSUE TITLE
Change remission copy prompt

### ISSUE THREAD

**Issue by tomwm** [ministryofjustice/atet#712]
From JOST: 
Copy below is what we would like added to whatever page gives details on where to send remission applications. Ideally we would like to have this in place in or around 5.5.15.

"The speediest and most efficient method of submitting your remission application and evidence is by email to eREMISSIONS@hmcts.gsi.gov.uk (England & Wales applications only).
If you choose to email your application you will receive an electronic acknowledgment of receipt.  Please do not send duplicates by post.

**Comment by tomwm** [comment]
https://www.employmenttribunals.service.gov.uk/remissions

**Comment by tomwm** [comment]
@michaelelwin this needs to go on:
-Your Fee page (where remission is indicated)
- Confirmation Page (when remission indicated)
- Confirmation email (When remission indicated)
- The guide where it talks about remssion

**Comment by michaelelwin** [comment]
Feel that the best way to encourage users to email their remission form is to add an extra step in the 'next steps' section of user email and completion page saying:  2. Email your completed fee remission application to eREMISSIONS@hmcts.gsi.gov.uk.

**Comment by michaelelwin** [comment]
have added to docs. eg https://docs.google.com/document/d/1PTRQtN2Z39pmJa0Hif9NfAiKJqw1ttKK_y9esdNVNbA/edit

**Comment by tomwm** [comment]
Hmmm. Let's wait to here back from Helen and Dan about the Scotish issue.
Although I guess we could code it to only show that if the claim is one to
be dealt with by England and Wales.

**Comment by tomwm** [comment]
![screen shot 2015-04-28 at 16 20 56](https://cloud.githubusercontent.com/assets/7645929/7373126/b660c078-edc2-11e4-9876-9e24338bae9e.png) @michaelelwin

**Comment by michaelelwin** [comment]
The copy for the completion pages is here: https://docs.google.com/document/d/1jRMeOHOAWBI-3FhUSywga7G28NNCioUQWyYGbqqIMms/edit#bookmark=id.l5pim3tldog8

The guide copy is here: 

https://docs.google.com/document/d/1TYCUjlZNuqIpS3a_iTE5HA_UqkHom7hcyDK-c2nT8mI/edit#bookmark=id.gbrg4uulr1py

**Comment by michaelelwin** [comment]
@Demwunz copy has changed in light of this morning's meeting with Dan and Helen = 

New copy for emails here (only changes if indicating remission)

https://docs.google.com/document/d/1PTRQtN2Z39pmJa0Hif9NfAiKJqw1ttKK_y9esdNVNbA/edit

New copy for submission pages here 

https://docs.google.com/document/d/1jRMeOHOAWBI-3FhUSywga7G28NNCioUQWyYGbqqIMms/edit#bookmark=id.ofmf02wxeawb
