### ISSUE TITLE
Character count on long free text fields

### ISSUE THREAD

**Issue by tomwm** [ministryofjustice/atet#732]
Claim details

**Comment by michaelelwin** [comment]
Text should be: 

Character count: 2500

With number decreasing as text is added.

**Comment by tomwm** [comment]
Hmmm does that make sense. That implies that it is the sum of characters which it isn't. Shouldn't it be 'Characters remaining' or something like that?

Does it go red at a certain value eg when 100 words remain?

**Comment by michaelelwin** [comment]
Fair point. How about:

2500 characters remaining

**Comment by tomwm** [comment]
Yeah, better. Or:

Characters remaining: 2500

So that the thing that changes is at the end of the sentence which feels
better. Not sure about the colon use though...

@demwunz you have the deciding vote



On 12 May 2015 at 11:53, Michael Elwin <notifications@github.com> wrote:

> Fair point. How about:
>
> 2500 characters remaining
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ministryofjustice/atet/issues/732#issuecomment-101235197>
> .
>



-- 
Tom Wynne-Morgan
Product Manager
*Ministry of Justice Digital Services*

*https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London
<https://www.google.com/calendar/embed?src=tom.wynne-morgan%40digital.justice.gov.uk&ctz=Europe/London>
*

tom.wynne-morgan@digital.justice.gov.uk <tom.dolan@digital.justice.gov.uk>
