### ISSUE TITLE
Direct all outbound correspondence to representative, if present.

### ISSUE THREAD

**Issue by tomwm** [ministryofjustice/atet#737]
If rep details are present, all outbound emails from the app should go to them and NOT the primary respondent

**Comment by dan-palmer** [comment]
- If one claimant and no rep we send conf. emails to them. 
- If one claimant and a rep we send conf. emails to both. 
- If multiple claimants (i.e. 2 or more) and a rep we just send to rep.

**Comment by dan-palmer** [comment]
@tomwm 

We already handle the issues raised here.

```ruby
# Extracted from claim_reviews_helper.rb
def email_addresses
    claimants = claim.claimants.pluck(:email_address)
    representatives = [claim.representative.try(:email_address)]
    (claimants + representatives).reject(&:blank?)
end
```

- At the moment we extract all of the email address from the claimants. 
- <b>We don't actually get email addresses from secondary claimants so this is a bit misleading</b>.
- We then attempt to get the email address from the representative if it exists.

In summary the only permutations of emails we send are:
- the primary claimant
- the rep
- the primary claimant & the rep
- no emails(no rep & primary claimant didn't provide email)

There is the case where the user un-ticks emails on the review page though.

**Comment by dan-palmer** [comment]
![screen shot 2015-05-18 at 15 39 48](https://cloud.githubusercontent.com/assets/1006365/7683017/2544f52a-fd74-11e4-82fa-9a8affa612d5.png)

**Comment by tomwm** [comment]
Ah right. I think that is the bit that people are missing. So, if a rep is filling it in, they are not unchecking the primary claimant box. 

We've known for a while that the functionality to do this should be separate from the reviewing claim page to solve this issue, but that wont get done now.

Not showing the primary claimant at all is not a good move. But perhaps in the instances of multiple claimants with a rep, the claimants box could be unchecked by default?

If not, then its probably a no go as a feature.

**Comment by dan-palmer** [comment]
Yeah, we can have it so that we leave the primary claimant unchecked in that case.
