### ISSUE TITLE
Service offline page

### ISSUE THREAD

**Issue by tomwm** [ministryofjustice/atet#786]
A page to point to from root in the event that fees are illegal and the service has to be taken down temporarily.

Copy on google doc. https://docs.google.com/a/digital.justice.gov.uk/document/d/1OsF4IbGt4hDGXR91yS70hRS6HM9ThgaSgk7AKKZkOMw/edit?usp=sharing

**Comment by Demwunz** [comment]
https://github.com/ministryofjustice/atet/tree/issues-786
