### ISSUE TITLE
Help With Fees Link

### ISSUE THREAD

**Issue by dthomps1** [ministryofjustice/atet#803]
Linked to 797 - the remission link does not work -  redirect must have been disabled - needs updating to http://hmctsformfinder.justice.gov.uk/HMCTS/GetLeaflet.do?court_leaflets_id=2833 (probably)

**Comment by tomwm** [comment]
This looks like it has been done now and the link now directs to https://www.gov.uk/get-help-with-court-fees

So will close this ticket
